## Default site configuration

baseURL: https://tweets.micahrl.com
languageCode: en-us
title: Micah R Ledbetter Tweet Archive

theme:
- github.com/mrled/twarchive/aviary
- github.com/mrled/twarchive/ornithography

mediaTypes:
  text/netlify:
    delimiter: ""
    suffixes: [""]

outputFormats:
  tweet:
    basename: index.tweet
    # Process with Go's text/template, not html/template
    isPlainText: true
    mediaType: text/html
    notAlternative: false

outputs:
  home:
    - HTML
  section:
    - HTML
    - tweet

Params:
  dateform: "2006-01-02 03:04:05 -07:00"

disableKinds:
  - taxonomy
  - term
